# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cmu' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cmu
  pod 'Google-Mobile-Ads-SDK'


  target 'cmuTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'cmu-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cmu-tvOS

  target 'cmu-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
